# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [4]:
x = np.arange(10,50)

4. Find the shape of previous array in question 3

In [5]:
np.shape(x)

(40,)

5. Print the type of the previous array in question 3

In [6]:
x.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [7]:
np.__version__
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/anaconda\\Library\\include']


7. Print the dimension of the array in question 3


In [8]:
x.ndim

1

8. Create a boolean array with all the True values

In [9]:
np.ones(10, dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [10]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

10. Create a three dimensional array



In [11]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
x[5] =1
x

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [16]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [17]:
arr=arr.astype(np.float)
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [18]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [19]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
np.equal(arr1,arr2)

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [20]:
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
 
odd_values = (a%2 == 1) 
odd_values

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

18. Replace all odd numbers to -1 from previous array

In [21]:
a[odd_values] = -1 
a

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [22]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [23]:
array = np.ones((3, 3)) 
array = np.pad(array, pad_width=1, mode='constant', 
               constant_values=0)
array

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [24]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [25]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0][0:3] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [29]:
array = np.arange(0,9).reshape(3,3)
array
array[0][0:3]

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [31]:
array = np.arange(0,9).reshape(3,3)
array
array[1][0:3]

array([3, 4, 5])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [32]:
array = np.arange(0,9).reshape(3,3)
array
array[2][0:2]

array([6, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [45]:
rand2 = np.random.rand(10,10)
rand2


array([[0.6068463 , 0.76511393, 0.94600757, 0.26534105, 0.37923405,
        0.88887091, 0.93995826, 0.82581169, 0.65960927, 0.1377141 ],
       [0.14026839, 0.91672376, 0.07926089, 0.50238219, 0.12950403,
        0.18429261, 0.26150088, 0.72458482, 0.43203312, 0.69847374],
       [0.8837012 , 0.16227514, 0.14869174, 0.89548693, 0.82480543,
        0.78023867, 0.12661621, 0.55505665, 0.96371286, 0.01773255],
       [0.63989388, 0.18404846, 0.70317443, 0.14697719, 0.78676125,
        0.90702424, 0.20964129, 0.22541761, 0.97842773, 0.71689848],
       [0.88563302, 0.40135459, 0.65737882, 0.97003971, 0.44248204,
        0.63493156, 0.62674285, 0.75496402, 0.71619463, 0.5961187 ],
       [0.77279119, 0.0480785 , 0.4270806 , 0.21979761, 0.93002701,
        0.24188979, 0.77518098, 0.62866744, 0.10082356, 0.51735237],
       [0.79065112, 0.83020344, 0.77250987, 0.59861787, 0.05018187,
        0.57987817, 0.85147477, 0.6065543 , 0.59962581, 0.34975298],
       [0.17293955, 0.81085388, 0.1060932

In [46]:
np.min(rand2)


0.01765971842585401

In [47]:
np.max(rand2)

0.9784277299014772

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [51]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8]) 
np.intersect1d(a, b)


array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [52]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [59]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data

array([[ 0.7719125 ,  0.77831219, -1.40883794, -1.26110959],
       [-0.50719921,  0.10211107, -1.092806  , -1.69334092],
       [ 1.61511887, -1.76711329,  0.76853784, -1.023934  ],
       [-0.25421441, -0.86102466,  0.56807101, -2.40603159],
       [-0.9674667 ,  0.39383929, -0.06049794, -0.21822845],
       [ 0.55180694, -0.65911189, -0.02428802,  1.24025254],
       [-0.42386519,  0.49569674, -2.22205904,  1.56657377]])

In [61]:
data[names != 'Will']

array([[ 0.7719125 ,  0.77831219, -1.40883794, -1.26110959],
       [-0.50719921,  0.10211107, -1.092806  , -1.69334092],
       [-0.25421441, -0.86102466,  0.56807101, -2.40603159],
       [ 0.55180694, -0.65911189, -0.02428802,  1.24025254],
       [-0.42386519,  0.49569674, -2.22205904,  1.56657377]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [63]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data

array([[ 3.26605014e-01, -1.73681491e-01,  5.56146584e-01,
         6.11551226e-01],
       [ 4.25746501e-01,  1.19514703e+00, -5.10969020e-02,
         5.83781918e-01],
       [ 5.54902858e-01,  9.75628358e-01,  9.11699352e-04,
         1.37855497e+00],
       [ 4.59384766e-01,  9.12166556e-01,  1.86843887e+00,
        -9.81654572e-01],
       [ 1.06905837e+00,  8.08462216e-01,  8.47250508e-01,
         3.11462475e-01],
       [-1.10153270e+00,  2.32827803e-01,  1.21515098e+00,
        -1.24358067e+00],
       [ 4.26629954e-01, -3.94038646e-01, -3.50607925e-01,
        -9.44100258e-01]])

In [67]:
data[names != 'Will']
data[names != 'Joe']

array([[ 3.26605014e-01, -1.73681491e-01,  5.56146584e-01,
         6.11551226e-01],
       [ 5.54902858e-01,  9.75628358e-01,  9.11699352e-04,
         1.37855497e+00],
       [ 4.59384766e-01,  9.12166556e-01,  1.86843887e+00,
        -9.81654572e-01],
       [ 1.06905837e+00,  8.08462216e-01,  8.47250508e-01,
         3.11462475e-01]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [68]:
np.arange(1,16).reshape(5,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [70]:
a = np.arange(1,17).reshape(2,2,4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [71]:
np.swapaxes(a, 2, 0)

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [73]:
random = np.arange(10)
random

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
random = np.sqrt(random)
random

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [75]:
np.where(random<0.5,0,random)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [76]:
a = np.random.randint(12)
b = np.random.randint(12)
np.maximum(a,b)

10

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [78]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [79]:
set(names)

{'Bob', 'Joe', 'Will'}

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [81]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [82]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
sampleArray[1][:] = newColumn
sampleArray

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [83]:

x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [90]:
a = np.random.randint(50,75,(2,10))
a

array([[51, 52, 65, 54, 61, 68, 68, 58, 67, 62],
       [71, 59, 59, 59, 61, 56, 52, 56, 58, 73]])

In [91]:
np.cumsum(a)

array([  51,  103,  168,  222,  283,  351,  419,  477,  544,  606,  677,
        736,  795,  854,  915,  971, 1023, 1079, 1137, 1210], dtype=int32)